sudo: required
services:
  - docker

before_install:
  - docker build  -f Dockerfile.dev -t cicd_image .

script:
  - docker run cicd_image npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "ankit"
  env: "Ankit-env"
  bucket_name: "elasticbeanstalk-ap-south-1-364422983093"
  bucket_path: "ankit"

  on:
    branch: main
  
  access_key_id: $aws_access_key
  secret_access_key: 
   secure: $aws_secret_key
